name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps for matplotlib
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6 libpng16-16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: ruff check . || true

      - name: Run tests
        env:
          TELEGRAM_BOT_TOKEN: 'dummy'
          TELEGRAM_CHAT_ID: 'dummy'
        run: |
          pytest -q

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
